### ISSUE TITLE
Error in documentation 

### ISSUE THREAD

**Issue by vanxdium** [ha2pex/windcycle#1]
I've read the code and I'm pretty sure that links won't use the h2 style... 
https://github.com/ha2pex/windcycle/blob/6e8b46a76fd142bf5959511810504e3ca4c0454c/README.md?plain=1#L81

The code is made as when we use this function, the headings will take the styles of the links

**Comment by ha2pex** [comment]
Hey! I will fix it right now thanks for the suggestion
